perf: install allure in proper way under Dockerfile, check and setup allure in pipeline script

diff --git a/jenkins/jenkins_pipeline_script_sample.yml b/jenkins/jenkins_pipeline_script_sample.yml
--- a/jenkins/jenkins_pipeline_script_sample.yml
+++ b/jenkins/jenkins_pipeline_script_sample.yml
@@ -7,6 +7,23 @@ pipeline {
         string(name: 'BRANCH', defaultValue: 'master', description: 'Git branch to build')  // Add parameter for branch selection
     }
     stages {
+        stage('Check & Setup Allure') {                 // Check if Allure is installed
+            steps {
+                sh '''
+                    if ! which allure > /dev/null 2>&1; then
+                        echo "Allure not found. Installing Allure..."
+                        mkdir -p /usr/local/bin/allure
+                        curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.zip
+                        unzip -q allure.zip -d /usr/local/bin/allure
+                        rm allure.zip
+                        ln -s /usr/local/bin/allure/allure /usr/local/bin/allure
+                        echo "Allure installed successfully."
+                    else
+                        echo "Allure is already installed."
+                    fi
+                '''
+            }
+        }
         stage('Pulling from GitHub') {
             steps {
                 git branch: "${params.BRANCH}", url: 'https://github.com/harifrahman/selenium-sauce-demo.git'  // Use the branch parameter
@@ -36,7 +53,7 @@ pipeline {
                     retry(2) {  // Retry the test stage up to 2 times
                         sh '''
                             . ${PYTHON_ENV}/bin/activate
-                            pytest tests --alluredir=allure-results/unit || true
+                            pytest tests --alluredir=allure-results || true
                         '''
                     }
                 }
